import type { AgentId, AgentProfile } from "./types";

export const AGENTS: Record<AgentId, AgentProfile> = {
  quant: {
    id: "quant",
    name: "The Quant",
    role: "Momentum & technicals",
    model: "GPT-6 Astra",
    provider: "OpenAI",
    color: "#f4f4f5",
    body: "#fafafa",
    bodyShade: "#a1a1aa",
    head: "#ffffff",
    headShade: "#c9c9d1",
    persona: "Data-driven. Trusts indicators over narratives.",
  },
  degen: {
    id: "degen",
    name: "The Degen",
    role: "Momentum & conviction",
    model: "Grok 4.7",
    provider: "SpaceXAI",
    color: "#38bdf8",
    body: "#334155",
    bodyShade: "#0f172a",
    head: "#475569",
    headShade: "#1e293b",
    persona: "Follows the strongest movers. High conviction, clear sizing.",
  },
  guardian: {
    id: "guardian",
    name: "The Guardian",
    role: "Risk manager",
    model: "Claude Opus 4.8",
    provider: "Anthropic",
    color: "#fbbf24",
    body: "#ea8a2e",
    bodyShade: "#b45309",
    head: "#fbeedb",
    headShade: "#dcb98a",
    persona: "Sizes every position. Holds the veto.",
  },
  oracle: {
    id: "oracle",
    name: "The Oracle",
    role: "Probabilities & odds",
    model: "Jev",
    provider: "TypeSafe AI",
    color: "#f472b6",
    body: "#ec4899",
    bodyShade: "#be185d",
    head: "#fdf2f8",
    headShade: "#efb4d3",
    persona: "Speaks only in probabilities. Never trades a coin flip.",
  },
};

export const AGENT_ORDER: AgentId[] = ["quant", "degen", "guardian", "oracle"];
